//Matias Regalo 308940 | Juan Constantin 335718
package interfaz;

import dominio.*;
import interfaz.registrarAutor;
import interfaz.registrarEdit;
import interfaz.registrarGen;
import interfaz.registrarLibro;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author c
 */
public class Menu extends javax.swing.JFrame {

    private Sistema modelo;

    public Menu(Sistema unSistema) {
        modelo= unSistema;
        initComponents();
        setLocationRelativeTo(null);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuRegistro = new javax.swing.JMenu();
        menuRegistrarEdit = new javax.swing.JMenuItem();
        menuRegistrarGen = new javax.swing.JMenuItem();
        menuRegistrarAutor = new javax.swing.JMenuItem();
        menuRegistrarLibro = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        menuRegistroVenta = new javax.swing.JMenuItem();
        menuAnularVenta = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuConsultaLib = new javax.swing.JMenuItem();
        menuConsultaVenta = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Librerías -  Realizado por: Matías Regaló 308940 - Juan Constantin 335718");
        setLocation(new java.awt.Point(600, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menuRegistro.setMnemonic('f');
        menuRegistro.setText("   Registros ");

        menuRegistrarEdit.setMnemonic('o');
        menuRegistrarEdit.setText("Registrar editorial");
        menuRegistrarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarEditActionPerformed(evt);
            }
        });
        menuRegistro.add(menuRegistrarEdit);

        menuRegistrarGen.setMnemonic('s');
        menuRegistrarGen.setText("Registrar género");
        menuRegistrarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarGenActionPerformed(evt);
            }
        });
        menuRegistro.add(menuRegistrarGen);

        menuRegistrarAutor.setMnemonic('a');
        menuRegistrarAutor.setText("Registrar autor");
        menuRegistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarAutorActionPerformed(evt);
            }
        });
        menuRegistro.add(menuRegistrarAutor);

        menuRegistrarLibro.setMnemonic('x');
        menuRegistrarLibro.setText("Registrar libro");
        menuRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarLibroActionPerformed(evt);
            }
        });
        menuRegistro.add(menuRegistrarLibro);

        menuBar.add(menuRegistro);

        menuVenta.setMnemonic('e');
        menuVenta.setText("Ventas");

        menuRegistroVenta.setMnemonic('t');
        menuRegistroVenta.setText("Registro de venta");
        menuRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroVentaActionPerformed(evt);
            }
        });
        menuVenta.add(menuRegistroVenta);

        menuAnularVenta.setMnemonic('y');
        menuAnularVenta.setText("Anular venta");
        menuAnularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnularVentaActionPerformed(evt);
            }
        });
        menuVenta.add(menuAnularVenta);

        menuBar.add(menuVenta);

        menuConsulta.setMnemonic('h');
        menuConsulta.setText("Consultas");

        menuConsultaLib.setMnemonic('c');
        menuConsultaLib.setText("Consulta de libros");
        menuConsultaLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaLibActionPerformed(evt);
            }
        });
        menuConsulta.add(menuConsultaLib);

        menuConsultaVenta.setMnemonic('a');
        menuConsultaVenta.setText("Consulta de ventas");
        menuConsultaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaVentaActionPerformed(evt);
            }
        });
        menuConsulta.add(menuConsultaVenta);

        menuBar.add(menuConsulta);

        menuSalir.setMnemonic('h');
        menuSalir.setText("Salir");

        menuItemSalir.setMnemonic('a');
        menuItemSalir.setText("Salir ");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(menuItemSalir);

        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarLibroActionPerformed
        registrarLibro libro = new registrarLibro(modelo);
        libro.setVisible(true); 
    }//GEN-LAST:event_menuRegistrarLibroActionPerformed

    private void menuAnularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnularVentaActionPerformed
        anularFactura anular = new anularFactura (modelo);
        anular.setVisible(true); 
    }//GEN-LAST:event_menuAnularVentaActionPerformed

    private void menuRegistrarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarEditActionPerformed
        registrarEdit ed = new registrarEdit(modelo);
        ed.setVisible(true); 
    }//GEN-LAST:event_menuRegistrarEditActionPerformed

    private void menuRegistrarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarGenActionPerformed
        registrarGen gen = new registrarGen(modelo);
        gen.setVisible(true); 
    }//GEN-LAST:event_menuRegistrarGenActionPerformed

    private void menuRegistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarAutorActionPerformed
        registrarAutor autor = new registrarAutor(modelo);
        autor.setVisible(true); 
    }//GEN-LAST:event_menuRegistrarAutorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       try {  
        FileOutputStream ff = new FileOutputStream("ArchivoOb.ser");
        ObjectOutputStream out = new ObjectOutputStream(ff);
        out.writeObject(modelo);
        out.close();
     }
       catch(IOException e) { 
            JOptionPane.showMessageDialog(null, "Error de serializacion, se cargará el programa sin datos preguardados", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_formWindowClosed

    private void menuConsultaLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaLibActionPerformed
        ventanaConsultaLibro consultaLibro = new ventanaConsultaLibro(modelo);
        consultaLibro.setVisible(true);     }//GEN-LAST:event_menuConsultaLibActionPerformed

    private void menuRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroVentaActionPerformed
        registrarVenta venta = new registrarVenta (modelo);
        venta.setVisible(true); 
    }//GEN-LAST:event_menuRegistroVentaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            FileOutputStream ff = new FileOutputStream("ArchivoOb.ser");
            ObjectOutputStream out = new ObjectOutputStream(ff);
            out.writeObject(modelo); // Guarda el sistema
            out.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos al cerrar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        try {
            FileOutputStream ff = new FileOutputStream("ArchivoOb.ser");
            ObjectOutputStream out = new ObjectOutputStream(ff);
            out.writeObject(modelo); // Serializa y guarda el sistema
            out.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuConsultaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaVentaActionPerformed
        // TODO add your handling code here:
        consultarVenta venta = new consultarVenta (modelo);
        venta.setVisible(true); 
    }//GEN-LAST:event_menuConsultaVentaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem menuAnularVenta;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuConsultaLib;
    private javax.swing.JMenuItem menuConsultaVenta;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuRegistrarAutor;
    private javax.swing.JMenuItem menuRegistrarEdit;
    private javax.swing.JMenuItem menuRegistrarGen;
    private javax.swing.JMenuItem menuRegistrarLibro;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenuItem menuRegistroVenta;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables

}
