//Matias Regalo 308940 | Juan Constantin 335718
package interfaz;

import dominio.Sistema;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author c
 */
public class registrarEdit extends javax.swing.JFrame implements Observer {
private Sistema modelo;
    private DefaultTableModel tablemod; 
    /**
     * Creates new form ventanaRegistrar
     */
   
    public registrarEdit(Sistema unSistema) {
     modelo = unSistema;
     initComponents();
     initializeTableModel();
     setLocationRelativeTo(null);
     objetoAPantalla();
     modelo.addObserver(this);
     }

     public void update(Observable o, Object ob){
         objetoAPantalla();
     }
    
    private void initializeTableModel() {
        // Initialize the table model and set it to the table
        tablemod = new DefaultTableModel(new Object[][] {}, new String[] { "Nombre de editorial", "Nombre de pais de origen" });
        tabla.setModel(tablemod); // Set the model for the JTable
    }
     
    private void objetoAPantalla(){
        tablemod.setRowCount(0);
        for (int i = 0; i < modelo.getListaEditoriales().size(); i++){
        String nombreEdit = modelo.getListaEditoriales().get(i).getNombre();
        String nombrePais = modelo.getListaEditoriales().get(i).getPaisDeOrigen();

       Object[] data = {nombreEdit, nombrePais};

       tablemod.addRow(data);

    }
         txtNombreEdit.setText("");
         txtNombrePais.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        lblNombreEdit = new javax.swing.JLabel();
        lblNombrePais = new javax.swing.JLabel();
        txtNombrePais = new javax.swing.JTextField();
        txtNombreEdit = new javax.swing.JTextField();
        btnRegistrarEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblRegistrarEdit = new javax.swing.JLabel();
        btnCancelarEdit = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Libreria - Registro de editorial");
        setBackground(new java.awt.Color(255, 204, 204));
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(958, 800));
        getContentPane().setLayout(null);

        lblNombreEdit.setText("Nombre de editorial:");
        getContentPane().add(lblNombreEdit);
        lblNombreEdit.setBounds(70, 180, 200, 16);

        lblNombrePais.setText("Nombre de pais de origen:");
        getContentPane().add(lblNombrePais);
        lblNombrePais.setBounds(70, 220, 190, 16);
        getContentPane().add(txtNombrePais);
        txtNombrePais.setBounds(280, 220, 230, 22);
        getContentPane().add(txtNombreEdit);
        txtNombreEdit.setBounds(280, 180, 230, 22);

        btnRegistrarEdit.setText("Registrar");
        btnRegistrarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarEdit);
        btnRegistrarEdit.setBounds(620, 700, 140, 30);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre de editorial", "Nombre de pais de origen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 280, 440, 410);

        lblRegistrarEdit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRegistrarEdit.setText("Registrar Editorial");
        lblRegistrarEdit.setMaximumSize(new java.awt.Dimension(111, 150));
        lblRegistrarEdit.setMinimumSize(new java.awt.Dimension(111, 16));
        lblRegistrarEdit.setName(""); // NOI18N
        getContentPane().add(lblRegistrarEdit);
        lblRegistrarEdit.setBounds(30, 10, 366, 98);

        btnCancelarEdit.setText("Cancelar");
        btnCancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarEdit);
        btnCancelarEdit.setBounds(780, 700, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEditActionPerformed
        String nombreEdit = txtNombreEdit.getText();
        String nombrePais = txtNombrePais.getText();
        
        
          try {
    if (nombreEdit.isEmpty()  || nombrePais.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Deben estar completos todos los campos de texto antes de continuar.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        if(modelo.editUnico(nombreEdit)){
            modelo.registrarEdit(nombreEdit, nombrePais);
            JOptionPane.showMessageDialog(this, "La editorial "+ nombreEdit + " ha sido registrada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
             JOptionPane.showMessageDialog(this, "La editorial '" + nombreEdit + "' ya está en uso. Intente otro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
} catch (Exception e) {
    // Manejar errores inesperados
    JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el genero, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
}
      
        
    }//GEN-LAST:event_btnRegistrarEditActionPerformed

    private void btnCancelarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarEditActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEdit;
    private javax.swing.JButton btnRegistrarEdit;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreEdit;
    private javax.swing.JLabel lblNombrePais;
    private javax.swing.JLabel lblRegistrarEdit;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtNombreEdit;
    private javax.swing.JTextField txtNombrePais;
    // End of variables declaration//GEN-END:variables
}
