//Matias Regalo 308940 | Juan Constantin 335718
package interfaz;
import dominio.*;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.Observer;
import javax.swing.JOptionPane;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class registrarLibro extends javax.swing.JFrame implements Observer{
    private Sistema modelo;
    
    //inicializar modelo en el constructor
    public registrarLibro(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
        objetoAPantalla();
        setLocationRelativeTo(null);
        modelo.addObserver(this);
    }
    
      public void update(Observable o, Object ob){
         objetoAPantalla();
     }

    private void objetoAPantalla() {
        lstEditoriales.setListData(modelo.getListaEditoriales().toArray());
        lstGeneros.setListData(modelo.getListaGeneros());
        lstAutores.setListData(new String[0]);
        //limpiar campos de texto
        txtISBN.setText("");
        txtTitulo.setText("");
        txtCosto.setText("");
        txtVenta.setText("");
        txtStock.setText("");
        lblImagen.setText("                                       Sin Foto");
        lblImagen.setIcon(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtISBN = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtVenta = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAutores = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEditoriales = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGeneros = new javax.swing.JList();
        lblRegistrarLibro = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblPrecioVenta = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnFoto = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblLstEdit = new javax.swing.JLabel();
        lblLstGen = new javax.swing.JLabel();
        lblLstAut = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Libro");
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(958, 800));
        getContentPane().setLayout(null);
        getContentPane().add(txtISBN);
        txtISBN.setBounds(240, 530, 320, 22);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(240, 560, 320, 22);
        getContentPane().add(txtCosto);
        txtCosto.setBounds(240, 590, 320, 22);
        getContentPane().add(txtVenta);
        txtVenta.setBounds(240, 620, 320, 22);
        getContentPane().add(txtStock);
        txtStock.setBounds(240, 650, 320, 22);

        jScrollPane1.setViewportView(lstAutores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 150, 190, 350);

        lstEditoriales.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEditoriales);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 150, 200, 350);

        lstGeneros.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGenerosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstGeneros);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(360, 150, 200, 350);

        lblRegistrarLibro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRegistrarLibro.setText("Registrar Libro");
        lblRegistrarLibro.setMaximumSize(new java.awt.Dimension(111, 150));
        lblRegistrarLibro.setMinimumSize(new java.awt.Dimension(111, 16));
        lblRegistrarLibro.setName(""); // NOI18N
        getContentPane().add(lblRegistrarLibro);
        lblRegistrarLibro.setBounds(39, 26, 233, 48);

        lblISBN.setText("Codigo ISBN: ");
        getContentPane().add(lblISBN);
        lblISBN.setBounds(80, 530, 150, 16);

        lbltitulo.setText("Titulo: ");
        getContentPane().add(lbltitulo);
        lbltitulo.setBounds(80, 560, 150, 16);

        lblCosto.setText("Precio de Costo del Libro: ");
        getContentPane().add(lblCosto);
        lblCosto.setBounds(80, 590, 150, 16);

        lblPrecioVenta.setText("Precio de Venta del Libro: ");
        getContentPane().add(lblPrecioVenta);
        lblPrecioVenta.setBounds(80, 620, 150, 16);

        lblStock.setText("Stock: ");
        getContentPane().add(lblStock);
        lblStock.setBounds(80, 650, 140, 16);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(590, 720, 140, 30);

        btnFoto.setText("Cargar Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto);
        btnFoto.setBounds(80, 690, 480, 23);
        getContentPane().add(lblImagen);
        lblImagen.setBounds(590, 530, 308, 180);

        lblLstEdit.setText("Lista de editoriales:");
        getContentPane().add(lblLstEdit);
        lblLstEdit.setBounds(140, 120, 190, 16);

        lblLstGen.setText("Lista de generos:");
        getContentPane().add(lblLstGen);
        lblLstGen.setBounds(360, 120, 200, 16);

        lblLstAut.setText("Lista de autores:");
        getContentPane().add(lblLstAut);
        lblLstAut.setBounds(570, 120, 190, 16);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(760, 720, 140, 30);
        btnCancelar.getAccessibleContext().setAccessibleName("btnCancelar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        String ruta=" ";
        JFileChooser jFileChooser= new JFileChooser();
        FileNameExtensionFilter filtrador = new FileNameExtensionFilter("JPG", "jpg");
        jFileChooser.setFileFilter(filtrador);
        int resp= jFileChooser.showOpenDialog(this);
        if(resp== jFileChooser.APPROVE_OPTION) { 
            ruta = jFileChooser.getSelectedFile().getPath();
            
            Image imagen = new ImageIcon(ruta).getImage();
            ImageIcon icono =  new ImageIcon(imagen.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH));
            lblImagen.setIcon(icono);
        }
        String userHome = System.getProperty("user.home");
          String carpeta = userHome + File.separator + "Imagenes"; 
        File crearCarpeta = new File(carpeta);
        if(!crearCarpeta.exists()){   
            crearCarpeta.mkdirs();
        } 
        else{   
            JOptionPane.showMessageDialog(this,"Carpeta existente");
        }
        
         String archivo = "\\"+ txtISBN.getText() + ".jpg";
        File crearArchivo = new File(carpeta+archivo);
        try {
 Files.copy(jFileChooser.getSelectedFile().toPath(), crearArchivo.toPath(), StandardCopyOption.REPLACE_EXISTING);       
        } catch (IOException ex) {
            Logger.getLogger(registrarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String isbn = txtISBN.getText();
        String titulo = txtTitulo.getText();
       Editorial editorialSeleccionada = (Editorial) lstEditoriales.getSelectedValue();
        String genero = (String) lstGeneros.getSelectedValue();
        String autor = (String) lstAutores.getSelectedValue();

        
       
          int precioCosto; 
        int precioVenta; 
        int stock;
        
        
          try {
    if (isbn.isEmpty()  || titulo.isEmpty()  || genero.isEmpty() || autor.isEmpty() || editorialSeleccionada==null  || txtCosto.getText().isEmpty() || txtVenta.getText().isEmpty() || txtStock.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Deben estar completos y seleccionados todos los campos de texto antes de continuar.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        precioCosto = Integer.parseInt(txtCosto.getText());
        precioVenta = Integer.parseInt(txtVenta.getText());
        stock = Integer.parseInt(txtStock.getText());
    }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los campos de costo, venta y stock deben ser valores númericos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
    }
       
    if (stock < 0) {
            JOptionPane.showMessageDialog(this, "El stock debe ser mayor o igual a 0.");
            return;
        }

       if(modelo.libroUnico(isbn)){
          modelo.registrarLibro(autor, genero, editorialSeleccionada.getNombre(), isbn, titulo, precioCosto, precioVenta, stock);
                            JOptionPane.showMessageDialog(this, "El Libro " + titulo + " ha sido registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El ISBN '" + isbn + "' ya está en uso. Intente otro.", "Error", JOptionPane.ERROR_MESSAGE);
            }
} catch (Exception e) {
    // Manejar errores inesperados
    JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el libro, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void lstGenerosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGenerosValueChanged
          if (!evt.getValueIsAdjusting()) {  // Verifica que el usuario terminó de seleccionar
            // Obtén el género seleccionado
            String generoSeleccionado = (String) lstGeneros.getSelectedValue();
            if (generoSeleccionado != null) {
                // Llama a Sistema para obtener la lista de autores que escriben en el género seleccionado
                List<String> autoresFiltrados = modelo.getAutoresPorGenero(generoSeleccionado);
                // Actualiza lstAutores con los autores filtrados
                lstAutores.setListData(autoresFiltrados.toArray());
            }
        }
    }//GEN-LAST:event_lstGenerosValueChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLstAut;
    private javax.swing.JLabel lblLstEdit;
    private javax.swing.JLabel lblLstGen;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblRegistrarLibro;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JList lstAutores;
    private javax.swing.JList lstEditoriales;
    private javax.swing.JList lstGeneros;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
