//Matias Regalo 308940 | Juan Constantin 335718
package interfaz;
import dominio.Editorial;
import dominio.Sistema;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author c
 */
public class registrarAutor extends javax.swing.JFrame implements Observer {
    private Sistema modelo;
   
 
     public registrarAutor(Sistema unSistema) {
     modelo = unSistema;
     initComponents();
     setLocationRelativeTo(null);
     objetoAPantalla();
      modelo.addObserver(this);
     }

      public void update(Observable o, Object ob){
         objetoAPantalla();
     }
     
     private void objetoAPantalla(){
         lstAutores.setListData(modelo.getListaAutores());
         lstGenAutores.setListData(modelo.getListaGeneros());
         txtNombreAutor.setText("");
         txtNacionalidad.setText("");
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBoton31 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGenAutores = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        txtNombreAutor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAutores = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btnBoton32 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de autor");
        setBackground(new java.awt.Color(255, 204, 204));
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(958, 800));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre del autor:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 152, 170, 16);

        btnBoton31.setText("Registrar");
        btnBoton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton31ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBoton31);
        btnBoton31.setBounds(590, 600, 140, 30);

        jLabel2.setText("Nacionalidad:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 203, 160, 16);

        jLabel3.setText("Seleccionar cuales son los generos en los que el autor escribe");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 262, 440, 27);

        jScrollPane1.setViewportView(lstGenAutores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(43, 295, 440, 130);

        jLabel4.setText("Autores ingresados");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 449, 350, 27);
        getContentPane().add(txtNacionalidad);
        txtNacionalidad.setBounds(280, 200, 204, 23);

        txtNombreAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAutorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreAutor);
        txtNombreAutor.setBounds(280, 149, 204, 23);

        jScrollPane2.setViewportView(lstAutores);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(43, 482, 440, 130);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Registrar Autor");
        jLabel5.setMaximumSize(new java.awt.Dimension(111, 150));
        jLabel5.setMinimumSize(new java.awt.Dimension(111, 16));
        jLabel5.setName(""); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(43, 53, 366, 78);

        btnBoton32.setText("Cancelar");
        btnBoton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton32ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBoton32);
        btnBoton32.setBounds(760, 600, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBoton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton31ActionPerformed
        String nombre =  txtNombreAutor.getText();
        String nacionalidad = txtNacionalidad.getText();
        List<String> generosSeleccionados = lstGenAutores.getSelectedValuesList(); 
      
    
        try {
    if (nombre.isEmpty()  || nacionalidad.isEmpty()  || generosSeleccionados.isEmpty() ) {
        JOptionPane.showMessageDialog(this, "Deben estar completos y seleccionados todos los campos de texto antes de continuar.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

   if(modelo.autorUnico(nombre)){
    modelo.registrarAutor(nombre, nacionalidad, generosSeleccionados);
     JOptionPane.showMessageDialog(this, "El autor "+ nombre + " ha sido registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
   }  
else {
     JOptionPane.showMessageDialog(this, "El nombre '" + nombre + "' ya está en uso. Intente otro.", "Error", JOptionPane.ERROR_MESSAGE);
}
} catch (Exception e) {
    // Manejar errores inesperados
    JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el autor, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnBoton31ActionPerformed

    private void txtNombreAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAutorActionPerformed

    private void btnBoton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton32ActionPerformed
dispose();
    }//GEN-LAST:event_btnBoton32ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton31;
    private javax.swing.JButton btnBoton32;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstAutores;
    private javax.swing.JList<String> lstGenAutores;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombreAutor;
    // End of variables declaration//GEN-END:variables
 }

