//Matias Regalo 308940 | Juan Constantin 335718
package interfaz;

import dominio.Sistema;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
public class registrarGen extends javax.swing.JFrame implements Observer {
private Sistema modelo;
    
    /**
     * Creates new form registrarGen
     */
     public registrarGen(Sistema unSistema) {
     modelo = unSistema;
     initComponents();
     objetoAPantalla();
     setLocationRelativeTo(null);
      modelo.addObserver(this);
     }
     
       
     public void update(Observable o, Object ob){
         objetoAPantalla();
     }
     
      private void objetoAPantalla(){
         lstGen.setListData(modelo.getListaGeneros());
         txtNombreGen.setText("");
         txtDesc.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreGen = new javax.swing.JLabel();
        btnRegistrarGen = new javax.swing.JButton();
        lblDesc = new javax.swing.JLabel();
        txtNombreGen = new javax.swing.JTextField();
        txtDesc = new java.awt.TextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGen = new javax.swing.JList<>();
        lblRegistrarGen = new javax.swing.JLabel();
        lblGeneroIng = new javax.swing.JLabel();
        btnCancelarRegistroGen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de género");
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(958, 800));
        getContentPane().setLayout(null);

        lblNombreGen.setText("Nombre del género:");
        getContentPane().add(lblNombreGen);
        lblNombreGen.setBounds(70, 210, 120, 16);

        btnRegistrarGen.setText("Registrar");
        btnRegistrarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarGenActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarGen);
        btnRegistrarGen.setBounds(590, 720, 140, 30);

        lblDesc.setText("Descripción:");
        getContentPane().add(lblDesc);
        lblDesc.setBounds(70, 260, 120, 90);
        getContentPane().add(txtNombreGen);
        txtNombreGen.setBounds(210, 210, 310, 22);
        getContentPane().add(txtDesc);
        txtDesc.setBounds(210, 260, 310, 90);

        jScrollPane3.setViewportView(lstGen);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(70, 410, 450, 310);

        lblRegistrarGen.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRegistrarGen.setText("Registrar Genero");
        lblRegistrarGen.setMaximumSize(new java.awt.Dimension(111, 150));
        lblRegistrarGen.setMinimumSize(new java.awt.Dimension(111, 16));
        lblRegistrarGen.setName(""); // NOI18N
        getContentPane().add(lblRegistrarGen);
        lblRegistrarGen.setBounds(40, 40, 329, 99);

        lblGeneroIng.setText("Generos ingresados:");
        getContentPane().add(lblGeneroIng);
        lblGeneroIng.setBounds(70, 380, 330, 16);

        btnCancelarRegistroGen.setText("Cancelar");
        btnCancelarRegistroGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistroGenActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarRegistroGen);
        btnCancelarRegistroGen.setBounds(750, 720, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarGenActionPerformed
         String nombreGen =  txtNombreGen.getText();
        String desc = txtDesc.getText();
        
        
           try {
    if (nombreGen.isEmpty()  || desc.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Deben estar completos todos los campos de texto antes de continuar.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if(modelo.genUnico(nombreGen)){
        modelo.registrarGen(nombreGen, desc);
        JOptionPane.showMessageDialog(this  , "El Genero " + nombreGen + " ha sido registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
         else {
            JOptionPane.showMessageDialog(this, "El Genero '" + nombreGen + "' ya está en uso. Intente otro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
} catch (Exception e) {
    // Manejar errores inesperados
    JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el genero, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
}
        
       
    }//GEN-LAST:event_btnRegistrarGenActionPerformed

    private void btnCancelarRegistroGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistroGenActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarRegistroGenActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRegistroGen;
    private javax.swing.JButton btnRegistrarGen;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblGeneroIng;
    private javax.swing.JLabel lblNombreGen;
    private javax.swing.JLabel lblRegistrarGen;
    private javax.swing.JList<String> lstGen;
    private java.awt.TextArea txtDesc;
    private javax.swing.JTextField txtNombreGen;
    // End of variables declaration//GEN-END:variables
}
