 //Matias Regalo 308940 | Juan Constantin 335718
package interfaz;

import dominio.Libro;
import dominio.Sistema;
import interfaz.LibroListener;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author c
 */
public class ventanaConsultaLibro extends javax.swing.JFrame implements Observer{
    private Sistema modelo;

    /**
     * Creates new form ventanaConsultaLibro
     */
    public ventanaConsultaLibro(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
        objetoAPantalla();
        setLocationRelativeTo(null);
        modelo.addObserver(this);
    }

    public void update(Observable o, Object ob){
         objetoAPantalla();
    }
    
    private void objetoAPantalla(){
         txtGen.setText("");
         txtAutor.setText("");
         txtTit.setText("");
        panelGrilla.removeAll();
        panelGrilla.revalidate();
        panelGrilla.repaint();
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsultarLibro = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        txtGen = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        panelGrilla = new javax.swing.JPanel();
        txtTit = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Libro");
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(958, 800));
        getContentPane().setLayout(null);

        lblConsultarLibro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblConsultarLibro.setText("Consultar Libro");
        lblConsultarLibro.setMaximumSize(new java.awt.Dimension(111, 150));
        lblConsultarLibro.setMinimumSize(new java.awt.Dimension(111, 16));
        lblConsultarLibro.setName(""); // NOI18N
        getContentPane().add(lblConsultarLibro);
        lblConsultarLibro.setBounds(50, 40, 329, 99);

        lblGenero.setText("Género");
        getContentPane().add(lblGenero);
        lblGenero.setBounds(60, 640, 110, 30);

        lblTitulo.setText("Título");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(60, 700, 120, 30);

        lblAutor.setText("Autor");
        getContentPane().add(lblAutor);
        lblAutor.setBounds(60, 590, 100, 30);
        getContentPane().add(txtGen);
        txtGen.setBounds(140, 640, 370, 40);

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(Consultar);
        Consultar.setBounds(560, 720, 140, 30);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(720, 720, 140, 30);

        panelGrilla.setLayout(new java.awt.GridLayout(1, 1));
        getContentPane().add(panelGrilla);
        panelGrilla.setBounds(50, 140, 880, 400);
        getContentPane().add(txtTit);
        txtTit.setBounds(140, 690, 370, 40);
        getContentPane().add(txtAutor);
        txtAutor.setBounds(140, 580, 370, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
      String autor =  txtAutor.getText();
      String genero = txtGen.getText();
      String titulo = txtTit.getText();
        
        List<Libro> librosFiltrados = new ArrayList<>();
    for (Libro libro : modelo.getListaLibros()) {
        if ((!autor.isEmpty() && libro.getAutor().toLowerCase().contains(autor.toLowerCase())) ||
            (!titulo.isEmpty() && libro.getTitulo().toLowerCase().contains(titulo.toLowerCase())) ||
            (!genero.isEmpty() && libro.getGenero().toLowerCase().contains(genero.toLowerCase()))) {
            librosFiltrados.add(libro);
        }
    }
    if(librosFiltrados.size()==0){
        JOptionPane.showMessageDialog(this, "No se ha encontrado ningún libro con los filtros establecidos, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
    } else{
        mostrarLibrosEnPanel(librosFiltrados);
    }
     

    }//GEN-LAST:event_ConsultarActionPerformed

    
private void mostrarLibrosEnPanel(List<Libro> librosFiltrados) {
        panelGrilla.removeAll();
        int columnas; 
          int cantidadLibros = librosFiltrados.size();
          if(cantidadLibros<4){
              columnas=cantidadLibros;
          }
          else{
              columnas=3;
          }
         int filas = (int) Math.ceil((double) cantidadLibros / columnas);
          panelGrilla.setLayout(new GridLayout(filas, columnas,10,10));
          int anchoPanel = panelGrilla.getWidth();
            int altoPanel = panelGrilla.getHeight();
            int anchoBoton = anchoPanel / columnas;
            int altoBoton = altoPanel / filas;
        // Mostrar los libros encontrados en el panel
        for (Libro libro :  librosFiltrados ) {
            JButton nuevo = crearBotonLibro(libro, anchoBoton, altoBoton);
            panelGrilla.add(nuevo);
        }
        
        // Actualizar la interfaz gráfica
        panelGrilla.revalidate();
        panelGrilla.repaint();
        
        
       
      }
    private JButton crearBotonLibro(Libro libro, int anchoBoton, int altoBoton) {
        String carpetaImagenes = System.getProperty("user.home") + File.separator + "Imagenes";
        String archivoImagen = carpetaImagenes + "\\" + libro.getIsbn() + ".jpg";
        
        JButton botonLibro = new JButton();
        
        // Verificar si existe una imagen para el libro
        File imagenArchivo = new File(archivoImagen);
        if (imagenArchivo.exists()) {
            ImageIcon iconoOriginal = new ImageIcon(archivoImagen);
            Image imagenEscalada  = iconoOriginal.getImage().getScaledInstance(anchoBoton, altoBoton,  Image.SCALE_SMOOTH);
            botonLibro.setIcon(new ImageIcon(imagenEscalada));
        } else {
            botonLibro.setText(libro.getIsbn()); 
        }
        
        // Agregar un ActionListener para mostrar detalles al hacer clic en el botón
        botonLibro.addActionListener(new LibroListener(libro));
        return botonLibro;
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblConsultarLibro;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelGrilla;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtGen;
    private javax.swing.JTextField txtTit;
    // End of variables declaration//GEN-END:variables


}
